#---------------------------------------------------------------------------------------------------------------------#
#                                                                                                                     #
#                                                                                                                     #
#                                                                                                                     #
#                                                                                                                     #
#                                                                                                                     #
#---------------------------------------------------------------------------------------------------------------------#

Tab_List:
  Header: "----------- &bShadow Realm &r-----------"

  Footer:

Log_Lag_Over_Milis: 100
Debug: []
Version: 1
